engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths: []